### ISSUE TITLE
Gradio demo not returning correct output

### ISSUE THREAD

**Issue by AK391** [FanChiMao/SRMNet-thesis#1]
Hi, thanks for making the Gradio demo here https://huggingface.co/spaces/52Hz/SRMNet_thesis, I noticed it does not return the correct output at times, getting image from another user?

I think a queue and cache could be enabled also by doing

enable_queue=True
cache_examples=True in launch

**Comment by FanChiMao** [comment]
Thank you for reporting the bug and presenting the solution of this problem!! 🥰

However, I prefer to demo the results without cache, 
because it may let users think the restored images are another existing images.😐

I think I have fixed the mentioned bug by deleting the folder of input testing image after generating the restored image,
which is referred from the [**code**](https://huggingface.co/spaces/akhaliq/SwinIR/blob/main/predict.py) of yours (same avatar in HuggingFace😏).

I really appreciate you publish the  awesome spaces in [**HuggingFace**](https://huggingface.co/akhaliq) which helps me a lot to upload my models to the platform!

Thank you very much~
